name: test2
on:
  workflow_dispatch:
  
jobs:
  get_v2ray:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install requests'
        run: |
          pip install -r requirements.txt
      - name: 设置githup信息
        env:
          email: ${{ secrets.EMAIL }}
          username: ${{ secrets.USERNAME }}
        run: |
          git config --global user.name "$username"
          git config --global user.email "$email"
     
      - name: Run python script
        run: |
          python3 get_clash.py
      - name: commit
        run: |                 
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin main
          git add ./pub/*
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S')筛选节点"
      - name: 推送更改
        uses:  ad-m/github-push-action@master
        with:
          # github_token: ${{ secrets.TOKEN }}
          branch: main
