name: localserver

# 触发条件
on:
  workflow_dispatch:

  schedule:
    # - cron: '*/5 * * * *'
    # 表达式生成  https://crontab.guru/
    - cron: '0 */8 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
      with:
        node-version: '18.x'
    - name: Install Python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: '3.x'
    - name: Set Timezone
      run: sudo timedatectl set-timezone 'Asia/Tehran'
    - name: Install Requirements
      run: |
        pip install -r ./utils/requirements.txt
    - name: Running Tasks
      run: |
        # wget -O subconverter.tar.gz https://github.com/tindy2013/subconverter/releases/download/v0.7.2/subconverter_linux64.tar.gz
        # tar -zxvf subconverter.tar.gz -C ./
        # chmod +x ./subconverter/subconverter && nohup ./subconverter/subconverter >./subconverter.log 2>&1 &
        # python ./utils/test.py
        node ./localserver/index.js
        sleep 2
        python ./utils/test2.py
